- Assembly-CSharp/Handlers.cs
- Assembly-CSharp/ModHooks.cs
- Assembly-CSharp/Patches/HeroController.cs
dash vector before changing it. This makes DashVectorHook better resemble the other hooks that require returning an output.
This also makes the modding api 0.0002% more efficient when dashing becasue the following code is no longer called twice in a row in the absence of a mod using this hook:
AffectedByGravity(false);
ResetHardLandingTimer();
if (dash_timer > DASH_TIME)
{
FinishedDashing();
return;
}
> Add a vector to DashVectorHook method so mods can get the original

- Assembly-CSharp/Patches/PlayerData.cs
Simple fix for the blue health hook which currently does nothing. orig_UpdateBlueHealth() needs to be called before the hooks because orig_UpdateBlueHealth() immediately sets blue health to 0 before checking charms.
> Fix UpdateBlueHealth()

- Assembly-CSharp/Patches/HeroControllerStates.cs
- Assembly-CSharp/ReflectionHelper.cs
I don't really think it's necessary to have a modhook for this - since the cstate isn't saved, there's not really a reason to modify the result of the methods instead of simply modifying the cstate directly.
Actually that's not totally true - you may want to be able to log changes to the cstate, probably for research purposes I guess. But I don't think it's worth the hassle of modifying the prepatcher just for this specific use case.
> Use ReflectionHelper for get/set cstate

- Assembly-CSharp/ModHooks.cs
- Assembly-CSharp/ModLoader.cs
Fixes bug where all itogglable mods are set to false if the game is closed before modloading has finished - this can be reproduced by quitting out while a mod like [GeoLog](https://github.com/SFGrenade/GeoLog) is preloading.
I wrote it like this because I felt an event for after mods have finished loading might be useful; the natural use case would be to execute code that requires interoperability with other mods without needing to set your mod's load priority (although I guess it's also concievable that a mod might want to be an early subscriber to one event and a late subscriber to another).
(The alternative fix could be to simply check ModLoader.Loaded before saving global settings, I guess)
> Don't save modhooks global settings if mods haven't finished loading

- Assembly-CSharp/IMenuRegisteringMod.cs
- Assembly-CSharp/Menu/MenuUtils.cs
- Assembly-CSharp/ModListMenu.cs
Currently, most (probably all) ICustomMenuMods on modlinks copy their own version of one of the CreateMenuBuilder functions to create their mod menu (if they're not using a menu creating utility which itself does that) - given that it's already in the MAPI, making it part of the public API seems useful.
> Add a public method for creating the IMenuMod menu

- Assembly-CSharp/ModHooks.cs
- Assembly-CSharp/Patches/HeroController.cs
Problem: the previous commit was raising AfterTakeDamage whenever the knight took damage while invulnerable. That part of the routine only does anything if the hazardtype is 2(spikes) or 3(acid). It's dishonest, therefore, to raise it when hazardtype is 1(enemy) for example, because the game wasn't going to deal damage anyway. I think it's best to raise the event if the damage was going to be dealt - actually, the current behaviour raises the event if the knight wasn't going to take damage by virtue of having pd.InvinciTest or hc.takeNoDamage be true, but I think it's better to raise the event and force devs to check those fields if they really care (which is unlikely - InvinciTest isn't set in normal gameplay and takeNoDamage is only set in void heart climb as far as I can tell) to allow …
> Make the new application of AfterTakeDamage only be raised when it should

- Assembly-CSharp/AssemblyExtensions.cs
- Assembly-CSharp/Extensions/AssemblyExtensions.cs
- Assembly-CSharp/ModLoader.cs
The particular error this addresses is when some types in the assembly derive from types that are unavailable. This way, it is safe to define types derived from types in external mods when the external mods might not be available.
> Avoid throwing when constructing mods with soft dependencies missing

- Assembly-CSharp/Menu/Content/StaticContent.cs
- Assembly-CSharp/Menu/MenuResources.cs
- Assembly-CSharp/Menu/MenuUtils.cs
- Assembly-CSharp/ModListMenu.cs
Utilize vanilla `Language.Language.Get` for menu texts. "Version" is currently replcaed with "v", which is language-independent, since vanilla does not contain localization for it.
> Utilize vanilla localization for menus

- Assembly-CSharp/ModLoader.cs
The types of errors addressed by try-catch on GetPreloadNames are rare but came up in #rando-general last week and the added error message would have been useful.
Including version names can also help diagnose obscure errors when it's not clear which mod is responsible for the errors.
> Add more logging to mod loading

- Assembly-CSharp/ModListMenu.cs
This addresses the issue where they press the back button (focus key) while the Mods button is selected, while in-game rather than in menu.
> Fix one source of menu softlocks

- Assembly-CSharp/ModLoader.cs
- Assembly-CSharp/Patches/HeroController.cs
- Assembly-CSharp/Preloader.cs
- Assembly-CSharp/Utils/AssemblyExtensions.cs
- Assembly-CSharp/Utils/UnityExtensions.cs
Both of the methods in UnityExtensions are used all the time in mods, so it seems good to make them publically available in the MAPI.
Move extensions to the `Modding.Utils` namespace
> Extensions

- Assembly-CSharp/ModHooks.cs
- Assembly-CSharp/ModLoader.cs
- Assembly-CSharp/Patches/ObjectPool.cs
- Assembly-CSharp/Patches/OnScreenDebugInfo.cs
- Assembly-CSharp/Patches/SceneManager.cs
- Assembly-CSharp/Preloader.cs
It seems that people have been getting a bug where the second OnScreenDebugInfo awakes before preloading is finished, so the LoadModsInit coroutine is started a second time. This guards against that.
> Better guard against second mod load

- Assembly-CSharp/Mod.cs
I don't know how exactly users manage to get their global settings to be null but it happens fairly often in #modding-help and I believe it should not be mods' responsibility to guard against the MAPI giving them null.
> Never load null global settings

- Assembly-CSharp/ModLoader.cs
Typically this issue arises if the user manually installed a mod and then installed it with Scarab or something like that. In such cases it's uniformly an error (sometimes without significant effect) so I feel like refusing to load such mods in that case is correct.
> Enforce no mods with the same name

- Assembly-CSharp/ModHooks.cs
- Assembly-CSharp/Patches/GameManager.cs
- Assembly-CSharp/Patches/HeroController.cs
- Assembly-CSharp/Patches/InputHandler.cs
- Assembly-CSharp/Patches/PlayerData.cs
- PrePatcher/Program.cs
Summary of changes:
- References to fake singletons (PlayerData.Instance, HeroController.Instance etc) in ModHooks are removed.
- The prepatcher is updated to patch methods on nested types - this is most important with IEnumerator methods but there are some patched methods which it seems are generated from inline delegates.
- HeroController, GameManager and PlayerData have patched methods changed to correctly use GetBool rather than field accesses. (I'm not sure if all of these methods are supposed to behave like this, but if any are not then I think it would be nice to explicitly exclude them in the PrePatcher even if it would be redundant.)
> Replace remaining PlayerData field accesses with GetBool etc

- Assembly-CSharp/GlobalSuppressions.cs
- Assembly-CSharp/Patches/PlayerData.cs
In `PlayerData.orig_TakeHealth` there is a call to `PlayerData.TakeHealth`, which cause a part of the `amount` is passed through `ModHooks.TakeHealthHook` twice. This results in counter-intuitive behaviour.
For example, if a mod hooks `ModHooks.TakeHealthHook` with `damage => damage * 2` in order to double all the damage, then because of the above described mechanic, when the player have lifeblood and the damage exceeds lifeblood amount, the exceeding part of the damage will be doubled twice. (Same as the old bug in the base game)
AFAIK currently no mod relies on this mechanic or does something with `PlayerData.orig_TakeHealth`, so it will be a safe change.
> Prevent passing through ModHooks twice in a single TakeHealth call

- Assembly-CSharp/CanvasUtil.cs
By default, Unity UI images do not respect packing orientation. This means that sprites that have been packed flipped or rotated will appear flipped or rotated when using CreateImagePanel. `useSpriteMesh` fixes this (lack of) behavior by creating a mesh that respects the UV coordinates of the sprite, like `SpriteRenderer` does.
> Prevent atlas-packed images from being flipped

- Assembly-CSharp/CanvasUtil.cs
Original bug: `Modding.CanvasUtil.GetFont("Arial")` throws an `ArgumentException`.
> Make GetFont work when there are multiple fonts with the same name

- Assembly-CSharp/ModHooks.cs
- Assembly-CSharp/Patches/SceneManager.cs
The replacement for `SceneManager.DrawBlackBorders()` didn't actually put the borders in the scene, which led to differences in room dupe visibility between vanilla and modded installs. Subscribers to `ModHooks.DrawBlackBordersHook` will still be able to read and modify the list of borders before they are put into the scene.
> Actually draw black borders after ModHooks.DrawBlackBordersHook

- Assembly-CSharp/IMod.cs
- Assembly-CSharp/Mod.cs
- Assembly-CSharp/ModListMenu.cs
Discussion Points:
1) Is this functionality we really want? (Forcing a uniform naming convention isn't an unreasonable take, though I do like being able to factor out the method to decide the button text)
2) Is this the best approach? (Should the attribute go on the method, or should it be another interface to control the text, or something else)
3) Should the menu button label be cached? Currently it's recomputed every time they return to menu, but it could be cached as an extra field on ModInstance (or maybe somehow else)
> Menu button label

- Assembly-CSharp/ModLoader.cs
Examples: Vasi, RandomizerCore
To appease the support people who get issues when users don't have Vasi/RC/etc installed for whatever reason.
> Log when an assembly with no mods is loaded

- Assembly-CSharp/ModLoader.cs
Repro: if 0 mods request preloads through the standard mechanism but a mod requests preloads through the scene hooks
> Fix preloading bug

- Assembly-CSharp/Logger.cs
Description of error:
- Multi line message has Environment.Newline as the line sep (\r\n)
- Previously would be split on \n
- And joined by \r\n, so the new line sep is \r\r\n
> Fix log presentation on windows

- .github/workflows/build.yaml
- .github/workflows/pr.yaml
- .github/workflows/push.yaml
This updates the workflow to work with PRs. Specifically, it allows external branches PRing against this repository to access the binary archive repository deploy key.
While this is potentially vulnerable, testing has determined that it is not. As described in `pr.yaml`, the `pull_request_target` workflow trigger can only activate the workflow in the base repository, not the workflow files in the PR. This means the only point of "vulnerability" would be the build script. However, the github token used in the `pr` workflow has read only access to this repository, and the SSH key to the archive repository is both used with `persist-credentials: false`, and is also read only. The only reason the archive repository is private is to not explicitly just redistribute base Hollow Knight assets …
> Update workflow to work with PRs.

- Assembly-CSharp/Menu/MenuUtils.cs
The `MenuUtils` class contains an erroneous call to `UIManager#GoToDynamicMenu`, which instead should call `UIManager#UIGoToDynamicMenu`. The first returns the coroutine that the latter starts. Currently, the cancel action does not return the user to the menu screen denoted by `returnScreen`.
> Fix cancel action of horizontal option in menu utils
